Add script to install dependencies for installation using deb package
rushabh-v/linux_face_unlock pull request #19
Opened 2020-10-19 16:49 UTC by pulkitvyas08

2020-10-19 19:36 UTC, rushabh-v requested changes

2020-10-19 19:36 UTC, rushabh-v commented on dpkg_requirements.sh
> +apt-get install -y $DEPS
Remove `apt-get update`.
remove the variable and directly put it after `sudo apt install`.

And make it `sudo apt install` (use `sudo` and remove `-get`).

Also, add remaining deps (face-recognition and terminaltables).

2020-10-20 06:53 UTC, rushabh-v commented
The problem with running this script in the installation workflow is that you can't run a `dpkg` command inside another. (facerec will be installed using `dpkg -i` and `apt install` also runs `dpkg` behind the scenes.) So, I think we can just add documentation for installation using deb package and we can put the command to install the dependencies there. (in that case we wouldn't need this script and we just need to specify the `sudo apt` deps there (the pip ones will be installed with the deb package)).

You can suggest a better idea if you have any.

Otherwise, you can start adding documentation for installation using the deb package and remove the shell script (Sorry for the chaos).
Link to the deb package: https://github.com/rushabh-v/linux_face_unlock/releases/download/v1.1/facerec_1.1_all.deb
Also, put a note that the deb package won't receive updates automatically. The PPA method is more preferable.

2020-10-20 06:58 UTC, pulkitvyas08 commented
I couldn't find a better way so I guess adding documentation would do fine for now. Should I add the documentation in the README file itself or make a separate markdown file?

2020-10-20 07:26 UTC, rushabh-v commented
Yes, append it in the readme itself. Thanks!

2020-10-20 11:20 UTC, rushabh-v requested changes

2020-10-20 11:20 UTC, rushabh-v commented on README.md
> +### Using .deb package
```suggestion
### Using deb package
```

2020-10-20 11:20 UTC, rushabh-v commented on README.md
> +#### 1. Download the latest release of Facerec from the releases section of the repository
` wget https://github.com/rushabh-v/linux_face_unlock/releases/download/v1.1/facerec_1.1_all.deb` to download it.

2020-10-20 11:20 UTC, rushabh-v commented on README.md
> +sudo dpkg -i <name of the .deb file>
```suggestion
sudo dpkg -i facerec_1.1_all.deb
```

2020-10-20 11:20 UTC, rushabh-v commented on README.md
> +sudo apt install -y python3-pip python3-opencv python3-setuptools python-execnet cmake libatlas-base-dev build-essential
put this as step 2 Because we require dependencies before installation of the deb package.

2020-10-20 13:29 UTC, rushabh-v requested changes

2020-10-20 13:29 UTC, rushabh-v commented on README.md
> +#### 1. Download the deb package of Facerec
```suggestion
#### 1. Download the deb package
```

2020-10-20 13:29 UTC, rushabh-v commented on README.md
> +#### 2. Install All the dependencies
```suggestion
#### 2. Install all the dependencies
```

2020-10-20 13:29 UTC, rushabh-v commented on README.md
> +#### 3. Install the .deb package on your machine using the command
```suggestion
#### 3. Install the deb package using
```

2020-10-20 13:31 UTC, rushabh-v commented
> Also, put a note that the deb package won't receive updates automatically. The PPA method is more preferable.

also, add this note.

2020-10-20 14:07 UTC, rushabh-v approved these changes

2020-10-20 14:07 UTC, rushabh-v commented
give @pulkitvyas08 25 points

2020-10-20 14:08 UTC, merged